# Generated by Django 3.1.2 on 2020-10-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=25)),
                ('capacity', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField()),
                ('farm_owner', models.CharField(max_length=25)),
            ],
        ),
    ]
