# Generated by Django 3.0.10 on 2020-10-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20201013_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_owner',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='owned_cats',
        ),
    ]
